/*
   This file was generated automatically by the Mojo IDE version B1.3.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_2 (
    input [7:0] a,
    input [7:0] b,
    output reg [7:0] s,
    input [5:0] alufn,
    output reg v,
    output reg n,
    output reg z
  );
  
  
  
  reg [8:0] sum;
  
  always @* begin
    s = 1'h0;
    sum = 1'h0;
    
    case (alufn)
      6'h00: begin
        s = a + b;
        sum = a + b;
      end
      6'h02: begin
        s = a * b;
        sum = a * b;
      end
      default: begin
        s = a - b;
        sum = a - b;
      end
    endcase
    n = sum[7+0-:1];
    v = (a[7+0-:1] & b[7+0-:1] & (~sum[7+0-:1])) | ((~a[7+0-:1]) & (~b[7+0-:1]) & sum[7+0-:1]);
    z = (~|sum);
  end
endmodule
